# Generated by Django 4.2.15 on 2024-09-16 17:31

from django.db import migrations

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_payment"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
