# Generated by Django 4.2.15 on 2024-09-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_payment_currency_payment_stripe_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="Сумма оплаты"),
        ),
    ]
