# Generated by Django 4.2.15 on 2024-09-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.URLField(blank=True, null=True, verbose_name="Видео"),
        ),
    ]
