# Generated by Django 4.2.15 on 2024-09-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0005_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Цена курса"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Цена урока"
            ),
            preserve_default=False,
        ),
    ]
